server:
  port: 8080
  api_prefix: /api/
  api_version: v1

security:
  enable_https: false
  https_port: 8180
  keystore: ${KEYSTORE_PATH:keystore.p12}
  keystore_password: ${KEYSTORE_PASSWORD:changeit}
  truststore: ${TRUSTSTORE_PATH:truststore.p12}
  truststore_password: ${TRUSTSTORE_PASSWORD:changeit}
  public_endpoints:
    - /auth/sign-in
    - /auth/sign-up
    - /auth/refresh
    - /swagger-ui/*any

jwt:
  expected_issuer: "https://veg-store.com"
  expected_audiences: [ "web", "mobile" ]
  access_duration: 15m
  refresh_duration: 7d
  private_key: ${PRIVATE_KEY:private.pem}
  public_key: ${PUBLIC_KEY:public.pem}

cors:
  allow_origins: [ "*" ]
  allow_methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
  allow_headers: [ "Content-Type", "Authorization" ]
  allow_credentials: true

swagger:
  host: ${SWAGGER_HOST:localhost:8080}

database:
  host: postgres
  port: 5432
  user: ${POSTGRES_USER:dummy}
  password: ${POSTGRES_PASSWORD:dummy}
  name: crud-sample
