app:
  name: Veg Store Backend
  version: ${APP_VERSION:1.0.0}
  enable_debug_logs: false # set to true to see all DEBUG level logs

server:
  port: 8080
  api_prefix: /api/
  api_version: v1
  default_locale: en

security:
  enable_https: false
  https_port: 8180
  keystore: ${KEYSTORE_PATH:keystore.p12}
  keystore_password: ${KEYSTORE_PASSWORD:changeit}
  truststore: ${TRUSTSTORE_PATH:truststore.p12}
  truststore_password: ${TRUSTSTORE_PASSWORD:changeit}
  public_endpoints:
    - /users/hello
    - /users/:id
    - /auth/
    - /auth/sign-up
    - /auth/refresh
    - /tasks/search
    - /tasks
    - /tasks/statuses
    - /swagger-ui/*any

jwt:
  expected_issuer: "https://veg-store.com"
  expected_audiences: [ "web", "mobile" ]
  access_duration: 15m
  refresh_duration: 7d
  private_key: ${PRIVATE_KEY:private.pem}
  public_key: ${PUBLIC_KEY:public.pem}

cors:
  allow_origins: [ "http://localhost:5173" ]
  allow_methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
  allow_headers: [ "Content-Type", "Authorization" , "No-Auth"]
  allow_credentials: true

swagger:
  host: ${SWAGGER_HOST:localhost:8080}

data:
  enable_data_seeding: false # set to "true" for the first time
  postgres:
    host: postgres
    port: 5432
    user: ${POSTGRES_USER:dummy}
    password: ${POSTGRES_PASSWORD:dummy}
    db_name: veg-store
    ddl_mode: update # create-drop | update | none, set to "create-drop" for the first time
    ssl:
      mode: verify-full # verify-full | disable
      root_cert: ${CA_CERT_PATH:ca/ca.crt}
      cert: ${CLIENT_CERT_PATH:veg-store-backend/server.crt}
      key: ${CLIENT_KEY_PATH:veg-store-backend/server.key}

