server:
  port: 8080
  api_prefix: /api/
  api_version: v2

cors:
  allowed_origins: "*"
  allowed_methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed_headers: "Content-Type, Authorization"

database:
  host: postgres
  port: 5432
  user: ${POSTGRES_USER:dummy}
  password: ${POSTGRES_PASSWORD:dummy}
  name: crud-sample
