basePath: /
definitions:
  dto.AdvancedFilterTaskRequest:
    properties:
      fromDate:
        example: "2001-12-31"
        type: string
      keyword:
        example: Task
        type: string
      sorts:
        description: dive to validate each element of slice
        items:
          $ref: '#/definitions/dto.SortTasksOption'
        type: array
      toDate:
        example: "2001-12-31"
        type: string
    type: object
  dto.CreateTaskRequest:
    properties:
      endDay:
        example: "2001-12-31"
        type: string
      startDay:
        example: "2001-12-31"
        type: string
      statusId:
        example: 5259ac80-1823-44d1-a701-0ed1e36fb38c
        type: string
      targetDay:
        example: "2001-12-31"
        type: string
      title:
        example: Create Task
        type: string
    required:
    - endDay
    - startDay
    - statusId
    - targetDay
    - title
    type: object
  dto.Direction:
    enum:
    - ASC
    - DESC
    type: string
    x-enum-varnames:
    - Asc
    - Desc
  dto.HttpResponse-any:
    properties:
      code:
        type: string
      data: {}
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-array_dto_PreviewStatus:
    properties:
      code:
        type: string
      data:
        items:
          $ref: '#/definitions/dto.PreviewStatus'
        type: array
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-array_dto_TaskItem:
    properties:
      code:
        type: string
      data:
        items:
          $ref: '#/definitions/dto.TaskItem'
        type: array
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-dto_OffsetPageResult-dto_TaskItem:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/dto.OffsetPageResult-dto_TaskItem'
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-dto_TaskItem:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/dto.TaskItem'
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-dto_Tokens:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/dto.Tokens'
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-model_User:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/model.User'
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.HttpResponse-string:
    properties:
      code:
        type: string
      data:
        type: string
      http_status:
        type: integer
      message:
        type: string
    type: object
  dto.OffsetPageResult-dto_TaskItem:
    properties:
      items:
        items:
          $ref: '#/definitions/dto.TaskItem'
        type: array
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  dto.PreviewStatus:
    properties:
      id:
        type: string
      title:
        type: string
    type: object
  dto.SignInRequest:
    properties:
      password:
        example: password123
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  dto.SortTasksOption:
    properties:
      direction:
        $ref: '#/definitions/dto.Direction'
      field:
        type: string
    type: object
  dto.TaskItem:
    properties:
      endDay:
        type: string
      id:
        type: string
      priority:
        type: integer
      startDay:
        type: string
      status:
        $ref: '#/definitions/dto.PreviewStatus'
      targetDay:
        type: string
      title:
        type: string
    type: object
  dto.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.UpdateTaskRequest:
    properties:
      endDay:
        example: "2001-12-31"
        type: string
      startDay:
        example: "2001-12-31"
        type: string
      statusId:
        example: 5259ac80-1823-44d1-a701-0ed1e36fb38c
        type: string
      targetDay:
        example: "2001-12-31"
        type: string
      title:
        example: Update Task
        type: string
    required:
    - endDay
    - startDay
    - statusId
    - targetDay
    - title
    type: object
  dto.UpdateTaskStatusRequest:
    properties:
      id:
        example: 5259ac80-1823-44d1-a701-0ed1e36fb38c
        type: string
      statusId:
        example: 5259ac80-1823-44d1-a701-0ed1e36fb38c
        type: string
    required:
    - id
    - statusId
    type: object
  model.User:
    properties:
      age:
        type: integer
      createdAt:
        type: string
      createdBy:
        type: string
      email:
        type: string
      id:
        type: string
      isDeleted:
        type: boolean
      name:
        type: string
      password:
        type: string
      sex:
        type: boolean
      updatedAt:
        type: string
      updatedBy:
        type: string
      version:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: benlun1201@gmail.com
    name: Nhan Le
    url: http://example.com/support
  description: This is an API document for veg-store-backend.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: RESTFUL API VERSION 1.0
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Authenticate user and return a token
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-dto_Tokens'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Sign in a user
      tags:
      - Auth
  /auth/me:
    get:
      description: Get name of a current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-any'
      security:
      - BearerAuth: []
      summary: Me
      tags:
      - Auth
  /tasks:
    get:
      consumes:
      - application/json
      description: Get All Tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-array_dto_TaskItem'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse-any'
      summary: Get All Tasks
      tags:
      - Tasks
    patch:
      consumes:
      - application/json
      description: Update existing task's status and return task id
      parameters:
      - description: Task status info
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTaskStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Update a task's status
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: Create new task and return task id
      parameters:
      - description: Task info
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Create a task
      tags:
      - Tasks
  /tasks/{id}:
    get:
      consumes:
      - application/json
      description: Get Task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-dto_TaskItem'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Get Task by ID
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: Update existing task and return task id
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Task info
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Update a task
      tags:
      - Tasks
  /tasks/search:
    post:
      consumes:
      - application/json
      description: Search tasks and return offset page
      parameters:
      - description: Filters
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.AdvancedFilterTaskRequest'
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-dto_OffsetPageResult-dto_TaskItem'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Search
      tags:
      - Tasks
  /tasks/statuses:
    get:
      consumes:
      - application/json
      description: Get All Preview Statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-array_dto_PreviewStatus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse-any'
      summary: Get All Statuses
      tags:
      - Tasks
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get details of a user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-model_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse-any'
      security:
      - BearerAuth: []
      summary: User details
      tags:
      - Users
  /users/hello:
    get:
      consumes:
      - application/json
      description: Anh trai say gex
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HttpResponse-string'
      summary: Anh trai say hi
      tags:
      - Users
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
